services:
  - type: web
    name: quotex-api
    env: python
    buildCommand: pip install -r requirements.txt && python -m playwright install chromium --with-deps
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 3000
      - key: PYTHONUNBUFFERED
        value: true
    plan: free
